Issue 45 vytvorit prehlad kreditov
Nexteria/Nextis pull request #104
Opened 2016-10-23 15:47 UTC by filek

Ešte sa čaká na konzultáciu od Sama a Lukáša, po dohode s Dušanom som urobil PR.

2016-10-23 15:47 UTC, ddeath commented
This pull request is now managed with CodeReviewHub. <a href='https://github.com/Nexteria/Nextis/pull/104'>Refresh</a>.<a href='#crh-update-none'></a>

2016-11-01 17:12 UTC, ddeath requested changes
Nejake postrehy som napisal, urcite to treba este prebehnut cez lintre, jedna php ale aj js

2016-11-01 17:12 UTC, ddeath commented on app/NxEventAttendee.php
> +        $result = [];
toto mozes napisat takto:

```
return $this->attendeesGroup->nxEvent;
```

2016-11-01 17:12 UTC, ddeath commented on app/User.php
> +        $eventAttendees = $this->eventAttendees()->get();
toto mozes napisat:

```
 $eventAttendees = $this->eventAttendees;
```

ak tam nedas zatvorky, vrati to collection, ak tam das zatvorky mas stale query

2016-11-01 17:12 UTC, ddeath commented on app/User.php
> +            if($event != null)
tu mozes vynechat != null

```
if ($event)
```

2016-11-01 17:12 UTC, ddeath commented on frontend/src/browser/users/ActivityPointsPage.js
> +
prazdne medzery na zvys

2016-11-01 17:12 UTC, ddeath commented on frontend/src/browser/components/Icon.js
> +        style={{ color: type == 'close' ? 'red' : 'green' }}
hmm toto sa mi moc nepozdava. Cize ikona moze byt iba cervena a zelena?

Mozno namiesto "type" by som tam dal ked tak "color"

2016-11-01 17:12 UTC, ddeath commented on frontend/src/browser/users/ActivityPointsPage.js
> +      </div>
Cele mi to pride ako prilis velka komponenta, rozbil by som to na mensie casti, minimalne na tie dve tabulky

2016-11-17 14:57 UTC, Player1os commented
Bug: Admin ma v prehlade https://files.slack.com/files-pri/T2AHMLX1U-F2T1Z1KRU/nexteria_space.clipular__3_.png0 bodov z NaN % (toto je aj v testovacom prostredi)

2016-11-17 15:06 UTC, Player1os commented
V nastaveniach uzivatela je teraz na spodku minimalny pocet aktivity bodov https://files.slack.com/files-pri/T2AHMLX1U-F2T29E0DV/nexteria_space.clipular__4_.png.

Toto ma vyznam len pre Nexteria Studentov, vieme to spravit tak aby to bolo len pre nich?

V buducnosti by sme chceli aby sa defaultny minimalny pocet kreditov odvijal od toho v ktorom leveli su ale na to potom spravime samostatny issue

2016-11-17 15:44 UTC, Player1os commented
Rozdelil by som stlpec https://files.slack.com/files-pri/T2AHMLX1U-F2T1Z1KRU/nexteria_space.clipular__3_.png v tomto obrazku na dva. Jeden nech ma celkovy pocet ziskanych kreditov "Bodov (% / možných)" na dva jeden nech je "Celkovy pocet bodov" a druhy nech je "% z minimalneho poctu".

Dovod preco to chceme je lebo chceme niekedy vediet zoradovat uzivatelov podla tychto cisel (podla % zvlast a podla poctu bodov zvlast)

2016-11-17 16:12 UTC, Player1os commented
S dandou sme sa zatial zhodli ze ten spodny panel kde je zoznam ostatnych uzivatel moze prekazat niektorym studentom, ak na tom Mato obzvlast netrval (este nemam jeho stanovsiko) dal by som to radsej prec
![vsetky eventy](https://cloud.githubusercontent.com/assets/2606397/20397103/cb21ae14-ace8-11e6-8674-aa37ede758c5.PNG)
kompromis by bolo tu cast kodu odkomentovat pre pripadne buduce pouzitie

2016-11-29 23:39 UTC, merged